### ISSUE TITLE
第二节课问题收集

### ISSUE THREAD

**Issue by loslakers** [FE-star/2019.03#5]

**Comment by sunmorg** [comment]
对封装，继承，多态不是特别理解，面试好像也经常会碰到问这种问题，是否有好的书籍或者文章吗？之前看过好多别人的文章，看了感觉似懂非懂，我自己实际中基本没有运用过多态这些东西，想补一下！

**Comment by viviScript** [comment]
在《你不知道的JavaScript》一书中写到：使用prototype去实现面向对象的方式是对JavaScript的一种误解与错误使用。es6中推出class的写法也只是<prototype>实现的一种语法糖，并不是真正理解JavaScript的一种方式。
在书中，作者推荐我们使用对象关联的思想去理解prototype机制，以面向委托的设计思路去使用prototype。在自己使用这种思路去实现demo后发现，理解方式很新颖，思路也较为清晰，以对象与对象之间的关系去理解prototype貌似更容易接受。
想请问老师：在JavaScript未来的发展中，这种面向委托，对象关联的设计是否是前端的正确方向，是否会普及使用，毕竟个人理解面向对象确实不适用JavaScript这种动态类型语言。

**Comment by ocean010101** [comment]
老师可以详细的讲解一下lianxi5么？

**Comment by loslakers** [comment]
@ocean010101  可以答疑的时候讲

**Comment by loslakers** [comment]
@viviScript 

我先帮你把相关的上下文补充一下

---
https://github.com/CuiFi/You-Dont-Know-JS-CN/blob/master/this%20%26%20object%20prototypes/ch4.md#javascript-%E7%9A%84%E7%B1%BB

> ### JavaScript 的“类”
> 在这个问题上 JavaScript 属于哪一边？JS 拥有 一些 像类的语法元素（比如 new 和 instanceof）有一阵子了，而且在最近的 ES6 中，还有一些追加的东西，比如 class 关键字（见附录A）。
>
> 但这意味着 JavaScript 实际上 拥有 类吗？简单明了：没有。
>
> 由于类是一种设计模式，你 可以，用相当的努力（正如我们将在本章剩下的部分看到的），近似实现很多经典类的功能。JS 在通过提供看起来像类的语法，来努力满足用类进行设计的极其广泛的 渴望。
>
> 虽然我们好像有了看起来像类的语法，但是 JavaScript 机制好像在抵抗你使用 类设计模式，因为在底层，这些你正在上面工作的机制运行的十分不同。`语法糖`和（极其广泛被使用的）JS “Class”库费了很大力气来把这些真实情况对你隐藏起来，但你迟早会面对现实：你在其他语言中遇到的 类 和你在 JS 中模拟的“类”不同。
>
> 总而言之，类是软件设计中的一种可选模式，你可以选择在 JavaScript 中使用或不使用它。因为许多开发者都对面向类的软件设计情有独钟，我们将在本章剩下的部分中探索一下，为了使用 JS 提供的东西维护类的幻觉要付出什么代价，和我们经历的痛苦。

---
https://github.com/CuiFi/You-Dont-Know-JS-CN/blob/master/this%20%26%20object%20prototypes/ch5.md#%E5%90%8D%E7%A7%B0%E7%9A%84%E6%84%8F%E4%B9%89%E4%BD%95%E5%9C%A8

> 这种机制常被称为“原型继承（prototypal inheritance）”（我们很快就用代码说明），它经常被说成是动态语言版的“类继承”。这种说法试图建立在面向类世界中对“继承”含义的共识上。但是 弄拧（意思是：抹平） 了被理解的语义，来适应动态脚本。
> 
> ...
> 
> 由于用语的模糊和歧义，我相信，对于解释 JavaScript 机制真正如何工作来说，“原型继承”这个标签（以及试图错误地应用所有面向类的术语，比如“类”，“构造器”，“实例”，“多态”等）本身带来的 危害比好处多。
> 
> “继承”意味着 拷贝 操作，而 JavaScript 不拷贝对象属性（原生上，默认地）。相反，JS 在两个对象间建立链接，一个对象实质上可以将对属性/函数的访问 委托 到另一个对象上。对于描述 JavaScript 对象链接机制来说，“委托”是一个准确得多的术语。
> 
> 另一个有时被扔到 JavaScript 旁边的术语是“差分继承”。它的想法是，我们可以用一个对象与一个更泛化的对象的 不同 来描述一个它的行为。比如，你要解释汽车是一种载具，与其重新描述组成一个一般载具的所有特点，不如只说它有四个轮子。
> 
> 如果你试着想象，在 JS 中任何给定的对象都是通过委托可用的所有行为的总和，而且 在你思维中你扁平化 所有的行为到一个有形的 东西 中，那么你就可以（八九不离十地）看到“差分继承”是如何自圆其说的。
> 
> 但正如“原型继承”，“差分继承”假意使你的思维模型比在语言中物理发生的事情更重要。它忽视了这样一个事实：对象 B 实际上不是一个差异结构，而是由一些定义好的特定性质，与一些没有任何定义的“漏洞”组成的。正是通过这些“漏洞”（缺少定义），委托可以接管并且动态地用委托行为“填补”它们。

---
https://github.com/CuiFi/You-Dont-Know-JS-CN/blob/master/this%20%26%20object%20prototypes/ch6.md

> 在你的软件体系结构中，类和继承是你可以 选用 或 不选用 的设计模式。多数开发者理所当然地认为类是组织代码的唯一（正确的）方法，但我们在这里看到了另一种不太常被提到的，但实际上十分强大的设计模式：行为委托。
>
> 行为委托意味着对象彼此是对等的，在它们自己当中相互委托，而不是父类与子类的关系。JavaScript 的 [[Prototype]] 机制的设计本质，就是行为委托机制。这意味着我们可以选择挣扎着在 JS 上实现类机制，也可以欣然接受 [[Prototype]] 作为委托机制的本性。
> 
> 当你仅用对象设计代码时，它不仅能简化你使用的语法，而且它还能实际上引领更简单的代码结构设计。
> 
> OLOO（链接到其他对象的对像）是一种没有类的抽象，而直接创建和关联对象的代码风格。OLOO 十分自然地实现了基于 [[Prototype]] 的行为委托。

**Comment by RayHSY** [comment]
老师，能不能讲解一下js的事件循环机制以及node.js的事件循环机制

**Comment by loslakers** [comment]
@WiessWong  可以

**Comment by boygod** [comment]
老师，有个问题，我很疑惑，代码如下：
  var Super = function () {}
  Super.prototype = Animal.prototype
  Cat.prototype = new Super()
以上这个情况，Cat的prototype的contructor属性指向的是Animal,需不需要手动给他置回Cat呢？

**Comment by FANZHETWO** [comment]
`function eventAgency() {
    this.tier = arguments[0], this.parn = arguments[1], this.fn = arguments[2], this.ret;
    return new eventAgency.prototype.method();
}
eventAgency.prototype.method = function () {
    if (tier.className == parn) fn(tier);
    if (pare(tier, parn, "className")) fn(ret);
    if (tier.id == parn) fn(tier);
    if (pare(tier, parn, "id")) fn(ret);
};
function pare(elem, elemP, type) {
    var cur = elem.parentNode;
    while (cur && cur.nodeType !== 9) {
        if (cur[type] == elemP) {
            this.ret = cur
            return true
        }
        cur = cur.parentNode;
    }
}`

老师 上面例子中new 一个函数原型链的的一个方法的构造函数，然后在在这个原型链方法里就可以直接取eventAgency  方法里定义的属性了。而且不加this。这是什么操作，有点晕。。请赐教。

**Comment by FANZHETWO** [comment]
```
function eventAgency() {
    this.tier = arguments[0],this.parn = arguments[1],this.fn = arguments[2],this.ret;
    return new eventAgency.prototype.method(); 
}
eventAgency.prototype.method = function () {
    if(tier.className==parn) fn(tier);
    if(pare(tier,parn,"className")) fn(ret);
    if(tier.id==parn) fn(tier);
    if(pare(tier,parn,"id")) fn(ret);
};
function pare(elem,elemP,type){
		var cur = elem.parentNode;
		while ( cur && cur.nodeType !== 9) {
			if(cur[type]==elemP) {
				this.ret=cur
				return true
			}
			cur = cur.parentNode;
		}
}
```
老师 上面例子中new 一个函数原型链的的一个方法的构造函数，然后在在这个原型链方法里就可以直接取eventAgency 方法里定义的属性了。而且不加this。这是什么操作，有点晕。。请赐教。

**Comment by ocean010101** [comment]
老师，什么情况下，使用了apply/call 函数之后，函数还会“丢失”自己原本的 this 绑定。

**Comment by boygod** [comment]
老师，问题如下：       
        function baz(){
            this.name="hty11"
            bar()
        }
        function bar(){
            console.log(this.name)
            this.name='hml'
        }
        baz()//hty11 这个可以理解，不用做解释
        var haha=new baz()
        //但是打印出的this.name为什么是hml,为什么this指向的是window呢，不应该指向的是new内部新创建的对象吗?
        //还有，按打印结果来看，打印出hml,但是为什么在赋值之前就能取到值了呢？

**Comment by boygod** [comment]
> 老师，什么情况下，使用了apply/call 函数之后，函数还会“丢失”自己原本的 this 绑定。

同学，你这个答案应该是，箭头函数的情况下

**Comment by boygod** [comment]
> 老师，什么情况下，使用了apply/call 函数之后，函数还会“丢失”自己原本的 this 绑定。

@ocean010101  同学，这个是使用箭头函数的情况下。

**Comment by FANZHETWO** [comment]
老师  exercise17  PubSub.js 里面
```
 let listeners = this.subscribers[type] = this.subscribers[type] || [];
```
this.subscribers[type] 写两边是啥原理呀。
