### ISSUE TITLE
第四节课问题收集

### ISSUE THREAD

**Issue by loslakers** [FE-star/2019.03#9]

**Comment by YvongYang** [comment]
正则表达式小数点匹配除换行符之外的任何单个字符。
例如，/.n/将会匹配 "nay, an apple is on the tree" 中的 'an' 和 'on'，但是不会匹配 'nay'。
老师我不是很明白为啥不会匹配'nay', 还有就是用exec方法输出的总是n和n前面的一个字符

**Comment by loslakers** [comment]
@YvongYang 
`/.n/` 和 `/n./` 是不一样的  nay 是匹配后者

**Comment by YvongYang** [comment]
我明白了，谢谢老师

**Comment by qikke** [comment]
http://www.cnblogs.com/coco1s/p/5777260.html
这篇文章中提到，用重写document.prototype.setAttribute的方法来阻止动态创建script标签，
var s = document.createElement('script'); s.setAttribute('src','xss'); 这样可以拦截。
但是如果这样写：
var s = document.createElement('script'); s.src='xss'; 该用什么方法拦截呢？

**Comment by loslakers** [comment]
@qikke
纠正一下，文章说的是重写 `Element.prototype.setAttribute`，事实上这个重写并不一定有效，因为存在以下几种情况可以绕开：

1. 使用 element.src 设置属性值
2. 使用 innerHTML 生成 script 标签
3. 直接用过 ajax 获取代码执行（不生成 script 标签）
4. 使用 document.write 生成 script 标签（文章要提到重写 document.write, 重写也不能完全避免）

防范 xss 的首要目标是不允许攻击脚本代码的执行，如果已经执行了，重写浏览器的默认方法只能说是`掩耳盗铃`，并没有从根本上杜绝这种攻击，应对运营商篡改代码，应该考虑的是使用 `HTTPS`、`CSP` 和 `SRI` 来防范

当然，运营商篡改代码的手段往往比较低级，很多情况下，重写浏览器的默认方法也是有效的

**Comment by welldeng** [comment]
@loslakers 
请问是否可以使用元编程手段检测这种重写的问题？
如果可以，如何检测所有的set赋值行为？

**Comment by qikee** [comment]
明白了，谢谢老师

**Comment by qikee** [comment]
像存储型XSS，比起纯前端渲染，服务端渲染发生的概率更高，可以这样理解吧
如果服务端渲染的html掺杂了攻击代码，前端阻止攻击代码运行的手段一般有哪些？（感觉重写浏览器方法很不靠谱），有没有检测上报的过程？老师所在的项目是怎么解决这种问题的呢
